name: Build Release Docker Image

on:
  workflow_call:
    inputs:
      extra-labels:
        description: 'Optional extra labels for the Docker build command'
        required: False
        type: 'string'
      artifact-name:
        required: false
        type: string
      artifact-path:
        required: false
        type: string
        default: "./"

jobs:

  build:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@main
      with:
        submodules: 'true'
    
    - name: Download artifact (default path)
      if: ${{ inputs['artifact-name'] != '' }}
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs['artifact-name'] }}
        path: "./_temp-artifact"

    - name: Move artifact to desired folder
      if: ${{ inputs['artifact-name'] != '' }}
      run: |
        mkdir -p "${{ inputs['artifact-path'] }}"
        mv ./_temp-artifact/* "${{ inputs['artifact-path'] }}/"

    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
    
    - name: Build the Docker image
      run: |
        IMAGE=ghcr.io/${{github.repository}}
        IMAGE=$(echo $IMAGE | tr '[A-Z]' '[a-z]')
        echo IMAGE: $IMAGE
        docker build . --file Dockerfile --no-cache -t $IMAGE ${{inputs.extra-labels}} --label RELEASE_TAG=${{github.event.release.tag_name}} --build-arg VERSION=${{github.event.release.tag_name}} --tag $IMAGE:${{github.event.release.tag_name}}
        docker push $IMAGE:${{github.event.release.tag_name}}
        
